[package]
name = "psh"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Uvizhev"]

[dependencies]
aes = "0.8.1"
anyhow = "1.0.64"
argon2 = "0.4.1"
cbc = "0.1.2"
home = "0.5.3"
once_cell = "1.14.0"
pickledb = "0.5.1"
serde = "1.0.144"
sha2 = "0.10.5"
thiserror = "1.0.34"
