[package]
name = "psh"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Uvizhev"]

[dependencies]
aes = "0.8"
anyhow = "1.0"
argon2 = "0.4"
cbc = "0.1"
home = "0.5"
once_cell = "1.13"
pickledb = "0.5"
serde = "1.0"
sha2 = "0.10"
thiserror = "1.0"
