[package]
name = "psh"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Uvizhev"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8"
anyhow = "1.0"
argon2 = "0.4"
cbc = "0.1"
clap = { version = "3.2", features = ["derive"] }
clipboard = "0.5"
console = "0.15"
ctrlc = "3.2"
dialoguer = "0.10"
home = "0.5"
once_cell = "1.13"
pickledb = "0.5"
serde = "1.0"
sha2 = "0.10"
thiserror = "1.0"
