[package]
name = "psh-cli"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Uvizhev"]

[workspace]
members = ["psh"]

[dependencies]
clap = { version = "3.2", features = ["derive"] }
clipboard = "0.5"
console = "0.15"
ctrlc = "3.2"
dialoguer = "0.10"

psh = { path = "psh" }
