[package]
name = "psh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5"
console = "0.15"
ctrlc = "3.2"
dialoguer = "0.10"
home = "0.5"
pickledb = "0.5"
rust-argon2 = "1.0"
serde = "1.0"
sha2 = "0.10"
