[package]
name = "psh-cli"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Uvizhev"]

[workspace]
members = ["psh"]

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
clipboard = "0.5.0"
console = "0.15.1"
ctrlc = "3.2.3"
dialoguer = { version = "0.10.2", features = ["zeroize"] }

psh = { path = "psh" }
